<!-- Solution for Program 2 - Dillon Fisher -->

<?php

// Functions
function radioButtons($fieldName, $buttonValues, $defaultButton = '') {
	// Do some error checking
	if (!is_string($fieldName)) {
		return "<p style=\"color:red;\">Error! Parameter 1 (fieldName) must be a single string.</p>";
	}
	if (!is_array($buttonValues)) {
		return "<p style=\"color:red;\">Error! Parameter 2 (buttonValues) must be an array of scalars.</p>";
	}
	if (isset($defaultButton)) {
		if (!is_scalar($defaultButton)) {
			return "<p style=\"color:red;\">Error! Paramter 3 (defaultButton) must be a scalar value.</p>";
		}
	}

	// Build the string containing the radio button's HTML code
	$result = "";
	foreach($buttonValues as $buttonValue) {
		// Preliminary error-checking
		if (!is_scalar($buttonValue)) {
			return "<p style=\"color:red;\">Error! Parameter 2 (buttonValues) must be an array of scalars.</p>";
		}
		$result .= "<input type=\"radio\" name=\"{$fieldName}\" value=\"{$buttonValue}\" ";
		if ($buttonValue == $defaultButton) $result .= "checked=\"checked\" ";
		$result .= "/> {$buttonValue} ";
	}

	return $result;
};

function picklist($fieldName, $optionValues, $defaultValues ='', $size = '') {
	// Do some error checking
	if (!is_string($fieldName)) {
		return "<p style=\"color:red\">Error! Parameter 1 (fieldName) must contain a string.</p>";
	}
	if (!is_array($optionValues)) {
		return "<p style=\"color:red;\">Error! Parameter 2 (optionValues) must contain an array of scalars.</p>";
	}
	if ($defaultValues != '') {
		if (!is_scalar($defaultValues)) {
			foreach($defaultValues as $defaultValue) {
				if (!is_scalar($defaultValue)) {
					return "<p style=\"color:red;\">Error! Parameter 3 (defaultValues) must contain either a scalar values or an array of scalar values.</p>";
				}
			}
		}
	}
	if ($size != '') {
		if (!(is_numeric($size) && is_scalar($size))) {
			return "<p style=\"color:red;\">Error! Parameter 4 (size) must contain a number.</p>";
		}
	}

	// Build the string containing the picklist's HTML code
	$result = "<select multiple=\"multiple\" name=\"{$fieldName}\" ";

	// Figure out if we need to add the size flag
	if (isset($size) and $size >= 1) {
		$result .= "size=\"{$size}\"";
	}

	// Close opening tag
	$result .= ">\n";

	foreach($optionValues as $optionValue) {
		// Preliminary error checking
		if (!is_scalar($optionValue)) {
			return "<p style=\"color:red;\">Error! Parameter 2 ($optionValues) must contain an array of scalars.</p>";
		}

		// Open tag for each option
		$result .= "\t\t\t<option";

		// Figure out if we need to add its selected flag
		if (is_scalar($defaultValues)) {
			if ($optionValue == $defaultValues) {
				$result .= " selected=\"selected\"";
			}
		} else if (is_array($defaultValues)) {
			if (in_array($optionValue, $defaultValues)) {
				$result .= " selected=\"selected\"";
			}
		}

		// Close beginning tag and set it's value
		$result .= ">{$optionValue}</option>\n";
	}

	// Close the select tag
	$result .= "</select>";

	return $result;
};

// Header material
echo '
<html>
<head>
	<title>Dillon Fisher - Program 6</title>
	<link href="style.css" rel="stylesheet" type="text/css">
</head>
<body>
	<div id="header">
		<p class="left">Dillon Fisher - CSCE 3420 - Program 6</p>
		<p class="right">Last Updated: ' . date('d F, Y H:i:s.', getlastmod()) . '</p>
	</div>';

// Main content
echo'
	<div id="input-wrapper">
		<p class="result-header">
			Please find below a demonstration of my input methods generated by functions.
		</p><br /><br />
		<p class="result-header">Radio buttons with a default checked set: '
			. radioButtons("theseButtons", array('one', 'two', 'three'), 'two') . '<br /><br />
			Radio buttons with no default checked: '
			. radioButtons("thoseButtons", array('one', 'two', 'three')) . '<br /><br />
			Radio buttons with some errors: '
			. radioButtons(5, array('one', 'two', 'three'), 'one') . '<br />'
			. radioButtons('arrayError', 'shouldBeArray', 'one') . '<br />'
			. radioButtons('defaultError', array('one', 'two', 'three'), array('wrong', 'no')) . '<br />'
			. radioButtons('arrayInArray', array('one', array('twoOne', 'twoTwo'), 'three'), 'one') .
		'</p><br /><br /><br />
		<p class="result-header">
			Pick list: '
			. pickList('thisList', array('one', 'two', 'three'), array('one', 'three'), 4) . '<br /><br />
			Pick list with no optional paramters: '
			. pickList('noOptionals', array('one', 'two', 'three', 'four', 'five')) . '<br /><br />
			Pick lists with some errors: <br/ >'
			. pickList(7, array('one', 'two')) . '<br />'
			. pickList('needsArray', 7) . '<br />'
			. pickList('arrayInArray', array('one', 'two'), array('one', array('twoOne', 'twoTwo'))) . '<br />'
			. pickList('nonNumericSize', array('one', 'two', 'three'), 'two','nope') . '
		</p>
	</div>';

// Finishing material
echo '
</body>
</html>';

?>
